### PR TITLE
Fix scipy version declaration

### PR DESCRIPTION
**Pull request by elatella**

### CODE REVIEW

**Review by vladanl — APPROVED** [review]
Thanks for spotting this

**Comment by bbarad** [comment]
It looks like this has been approved for a while - I'd like to make environment files that build directly off of this upstream rather than my fork, would it be possible to merge it?

**Comment by GenevieveBuckley** [comment]
I would also find this fix useful

**Comment by vladanl** [comment]
Thanks everybody and sorry for the delay

**Pull request merged**
