### PR TITLE
Create setup.py

### PR DESCRIPTION
**Pull request by bbarad**
This setup file lets you install the `pyto` package with `pip -e .` instead of needing to manually manage python path. Works well with pycurv.

### CODE REVIEW

**Comment by bbarad** [comment]
If you are onboard with incorporating this, I can add a more specific requirements list to make it even easier - as it stands most users are probably already going to have numpy, scipy, matplotlib, and pandas...

**Comment by bbarad** [comment]
@vladanl I just added a base set of requirements for the 4 packages you mention in the readme - this seems to install fine for me by pip!

**Comment by thorstenwagner** [comment]
Hi @bbarad ,

could you add the package future to the requirements. Otherwise it will not work.

Best,
THorsten

**Comment by bbarad** [comment]
Done - apologies, I had only tested on python 3.

**Comment by thorstenwagner** [comment]
Well, it is also a problem with python 3 (I'm actually using python 3).

For example the import `from past.builtins import basestring` in `utils/attributes.py` will fail if this the future package is not installed.

**Pull request merged**
